{
 "title": "svcproxy",
 "tags": [ "svcproxy" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response by code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_size_bytes_bucket{app=\"svcproxy\"}[5m])) by (code)",
     "legendFormat": "http/{{ code }}"
    }
   ]
  },
  {
   "title": "Requests per second by host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app=\"svcproxy\"}[5m])) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "transfers time vs transfers size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "write header time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_response_duration_seconds_sum[5m]))",
     "legendFormat": "response duration"
    },
    {
     "expr": "(sum(rate(http_request_size_bytes_sum{app=\"svcproxy\"}[5m]))+sum(rate(http_response_size_bytes_sum{app=\"svcproxy\"}[5m])))",
     "legendFormat": "bytes transferred"
    }
   ]
  },
  {
   "title": "Response latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum(irate(http_response_duration_seconds_bucket{app=\"svcproxy\"}[5m])) by (le))",
     "legendFormat": "1/10 𝜑"
    },
    {
     "expr": "histogram_quantile(0.25, sum(irate(http_response_duration_seconds_bucket{app=\"svcproxy\"}[5m])) by (le))",
     "legendFormat": "1/4 𝜑"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(http_response_duration_seconds_bucket{app=\"svcproxy\"}[5m])) by (le))",
     "legendFormat": "1/2 𝜑"
    },
    {
     "expr": "histogram_quantile(0.75, sum(irate(http_response_duration_seconds_bucket{app=\"svcproxy\"}[5m])) by (le))",
     "legendFormat": "3/4 𝜑"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(http_response_duration_seconds_bucket{app=\"svcproxy\"}[5m])) by (le))",
     "legendFormat": ".99  𝜑"
    }
   ]
  },
  {
   "title": "request / response sizes in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_sum{app=\"svcproxy\"}[5m]))",
     "legendFormat": "request"
    },
    {
     "expr": "sum(rate(http_response_size_bytes_sum{app=\"svcproxy\"}[5m]))",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{app=\"svcproxy\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod_name=~\"svcproxy.+\"}[5m]))",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{app=\"svcproxy\"})",
     "legendFormat": "FDs"
    }
   ]
  },
  {
   "title": "Go goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{app=\"svcproxy\"})",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{app=\"svcproxy\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(go_memstats_buck_hash_sys_bytes{app=\"svcproxy\"})",
     "legendFormat": "profiling bucket"
    },
    {
     "expr": "sum(go_memstats_gc_sys_bytes{app=\"svcproxy\"})",
     "legendFormat": "gc metadata"
    }
   ]
  },
  {
   "title": "Go GC duration duration vs bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{app=\"svcproxy\"})",
     "legendFormat": "gc_duration"
    },
    {
     "expr": "sum(go_memstats_next_gc_bytes{app=\"svcproxy\"})",
     "legendFormat": "next_gc_bytes"
    }
   ]
  },
  {
   "title": "Go memstats heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{app=\"svcproxy\"})",
     "legendFormat": "heap_alloc_bytes"
    },
    {
     "expr": "sum(go_memstats_heap_idle_bytes{app=\"svcproxy\"})",
     "legendFormat": "heap_idle_bytes"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{app=\"svcproxy\"})",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "sum(go_memstats_heap_sys_bytes{app=\"svcproxy\"})",
     "legendFormat": "heap_sys_bytes"
    }
   ]
  },
  {
   "title": "Go memstats heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_mcache_inuse_bytes{app=\"svcproxy\"})",
     "legendFormat": "mcache_inuse_bytes"
    },
    {
     "expr": "sum(go_memstats_mcache_sys_bytes{app=\"svcproxy\"})",
     "legendFormat": "mcache_sys_bytes"
    }
   ]
  },
  {
   "title": "Go memstats mspan",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_mspan_inuse_bytes{app=\"svcproxy\"})",
     "legendFormat": "mspan_inuse_bytes"
    },
    {
     "expr": "sum(go_memstats_mspan_sys_bytes{app=\"svcproxy\"})",
     "legendFormat": "mspan_sys_bytes"
    }
   ]
  }
 ]
}