dist: trusty
language: go
go:
  - "1.10"

services:
  - mysql
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"

before_install:
  - mysql -e 'CREATE DATABASE svcproxy;'
  - psql -c 'create database svcproxy;' -U postgres

script:
    - make dependencies test build-linux-amd64
